### ISSUE TITLE
Incorrect JSON value for some visgen bbdfs

### ISSUE THREAD

**Issue by pkhdipraja** [clp-research/clp-vision#6]
Line 88 in `ExtractFeats/extract.py` should be `obj_id` instead of `object_id` to match the output of `preproc.py`.
![bbdfs_bug](https://user-images.githubusercontent.com/28385774/58544997-b0d7f800-8202-11e9-9c70-dedcce660fae.png)

**Comment by davidschlangen** [comment]
oh yes, that makes sense. Feel free to change & make quick PR.
